- lib/html.dart
Looks like it is internally checking for arguments length. Always crashes with:
```
InvalidAccessError: Failed to execute 'close' on 'WebSocket': The code must be either 1000, or between 3000 and 4999. 0 is neither.
```
Chrome Version 51.0.2704.19 dev-m (64-bit)
> WebSocket.close doesn't like passing null arguments

- CHANGELOG.md
- analysis_options.yaml
- lib/html.dart
- lib/io.dart
- lib/src/copy/web_socket_impl.dart
- lib/status.dart
- pubspec.yaml
- add library names (fix the appearance in https://docs.flutter.io/)
- increase the sdk constraint to `<2.0.0-dev.infinity`
@nex3 @kevmoo 
(I think we'll want to publish this version after this lands; looks like only @nex3 is a publisher, which we'll probably want to expand a bit)
> add library names; increase the sdk constraint

- CHANGELOG.md
- lib/src/copy/bytes_builder.dart
- pubspec.yaml
Part of the rollout of https://github.com/dart-lang/sdk/issues/36900
> Declare a return value of `Uint8List` in `BytesBuilder` methods

- CHANGELOG.md
- lib/src/copy/web_socket_impl.dart
- pubspec.yaml
A recent change in the Dart SDK updated `Socket` to
implement `Stream<Uint8List>` rather than `Stream<List<int>>`.
This forwards compatible change calls `StreamTransformer.bind()`
rather than `Stream.transform()`, thus putting the stream in a
covariant position and allowing for the transition to `Uint8List`.
https://github.com/dart-lang/sdk/issues/36900
> Update to handle Socket implements Stream<Uint8List>

- test/io_test.dart
Replace `.toList()` for cases where we don't care about the collected
values.
Replace `.listen(null).asFuture()` since that is exactly the
implementation of `drain`.
> Use `drain` to reach end of stream in tests

- CHANGELOG.md
- lib/src/_connect_api.dart
- lib/src/_connect_html.dart
- lib/src/_connect_io.dart
- lib/src/channel.dart
- pubspec.yaml
- test/html_test.dart
- test/io_test.dart
This supports platform independent creation of WebSockets providing
the lowest common denominator of support on dart:io and dart:html.
> Add `WebSocketChannel.connect` factory constructor.

- lib/src/_connect_api.dart
- lib/src/_connect_html.dart
- lib/src/_connect_io.dart
- lib/src/channel.dart
This small PR adds an optional named argument to `WebSocketChannel.connect` so that it can pass custom socket protocols to the underlying platform specific implementation (both `HtmlWebSocketChannel` and `IOWebSocketChannel` supports it).
> Added optional [protocols] argument to [WebSocketChannel.connect]

- README.md
- lib/html.dart
- lib/io.dart
- lib/status.dart
Focus on the cross platform class in the README. From the issues we see
some folks aren't aware of the new `WebSocketChannel.connect`
constructor and get caught up with cross platform issues because they
originally picked single platform imports. The vast majority of use
cases are covered by the main import, so drop the sections on the
platform specific imports altogether.
Update some code samples in doc comments for style.
Remove some unnecessary library statements.
> Clean up some style

- .travis.yml
It's headless. Hopefully more stable.
> use chrome to test on Travis

- .travis.yml
- pubspec.yaml
- test/html_test.dart
Code snippets passed to `spawnHybridCode` are currently always run with
the SDK language version. Add an explicit language version marker so
that this test is stable.
> Add a language version tag in spawnHybridUri

- lib/src/copy/web_socket_impl.dart
- Switch to `List.filled` and fill with `0` to avoid difficulty during
the null safety migration.
- Add a generic type to avoid an unnecessary implicit dynamic.
> Fix usage of deprecated list ctor

- CHANGELOG.md
- pubspec.yaml
A local pub solve still won't pick it up due to a transitive constraint
from `analyzer` as a dev_dependency.
> Allow the null safe package:crypto

- analysis_options.yaml
- lib/html.dart
- lib/src/channel.dart
Switch to `ClassName.new` constructor tearoff syntax instead of the deprecated `new ClassName`.
Remove reference to deprecated lint `invariant_booleans`.
> Fix deprecated_new_in_comment_reference

- .github/workflows/test-package.yml
- CHANGELOG.md
- lib/io.dart
- pubspec.yaml
- test/io_test.dart
I am using a service that is very strict about user agents. Passing a user agent into the `headers` field doesn't work because this code adds headers instead of replacing them.
https://github.com/dart-lang/sdk/blob/83b7f7c2ac2df0a375387dc1017f6c96ccbcaccc/sdk/lib/_http/websocket_impl.dart#L1029
This PR allows passing in a custom http client to resolve the issue
> Allow passing through custom http client in IO socket connect

- CHANGELOG.md
- README.md
- example/example.dart
- lib/src/channel.dart
- pubspec.yaml
- Update the examples
- Updated the docs for [WebSocketChannel.ready]
Fixes https://github.com/dart-lang/web_socket_channel/issues/229
Fixes https://github.com/dart-lang/web_socket_channel/issues/249
Fixes https://github.com/dart-lang/web_socket_channel/issues/267
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package …
> Make it more clear how `WebSocketChannel.ready` should be used.

- lib/html.dart
---
<details>
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).
Note that many Dart repos have a weekly cadence for reviewing PRs - …
> Add a note explaining why the onerror doesn't generate detailed exception

- CHANGELOG.md
- lib/src/channel.dart
- pubspec.yaml
Closes #280
Errors during connection can cause confusion because they escape a try
block unless there is an `await channel.ready`. Mention that `ready` can
complete as an error in the case of connection failure.
> Mention `ready` in the docs for `connect`

- lib/html.dart
Use an if-case and destructure to new local variables to avoid some
throw-if-null operator usage.
> Drop some use of !

- lib/html.dart
- test/html_test.dart
`MessageEvent` is a `package:web` type and `data` field is a JS value of type `JSAny?`.
The receiving end of the `sink` is here: https://github.com/dart-lang/sdk/blob/26107a319a7503deafee404e3462644a873e2920/pkg/vm_service/lib/src/vm_service.dart#L1795
This code currently does not expect to see JS objects, so passing a `JSAny?` to the sink breaks it.
The fix should be in the generating end rather than the receiving end: `JSAny?` is supposed to be an unboxed value, not a boxed Dart value. In an ideal world we shouldn't be able to pass it as a Dart object. So we call `dartify` and convert it to a Dart object.
This fixes DevTools when compiled to Wasm: 
Thanks to @eyebrowsoffire and @mkustermann for help with debugging.
Also ping @srujzs for the issue with passing `JSAny?` as `Object?`.
> Fix JS value to Dart conversion when receiving from a web socket

- CHANGELOG.md
- pubspec.yaml
> Allow pkg:web v0.3.0

- CHANGELOG.md
- lib/src/copy/web_socket_impl.dart
- pubspec.yaml
> use secure random number generator

- CHANGELOG.md
- lib/io.dart
- lib/web_socket_adapter_web_socket_channel.dart
- pubspec.yaml
- test/io_test.dart
- test/web_socket_adapter_web_socket_test.dart
See [Simplify the web_socket_channel implementation](https://github.com/dart-lang/web_socket_channel/issues/340)
---
<details>
- Changes to packages require [corresponding …
> Implement IOWebSocketChannel as a WebSocketAdapterWebSocket subclass

- lib/adapter_web_socket_channel.dart
- pubspec.yaml
- test/adapter_web_socket_channel_test.dart
This issue was found in the SDK isolate stress tests:
https://github.com/dart-lang/sdk/issues/55538
---
<details>
- Changes to packages require [corresponding …
> Fix a race when close() called before remote class event delivered

- pubspec.yaml
Works around this issue:
```
Hey, I'm trying to release package:web_socket_channel:
dependency_overrides:
shelf_web_socket:
git:
ref: master
url: https://github.com/dart-lang/shelf.git
path: pkgs/shelf_web_socket
test: 1.25.2
package:shelf_web_socket:
dependency_overrides:
test: 1.25.2
And package:test
When I try to publish web_socket_channel, I get a warning that says: 
* Non-dev dependencies are overridden in pubspec.yaml.
This indicates you are not testing your package against the same versions of its
dependencies that users will have when they use it.
This might be necessary for packages with cyclic dependencies.
Please be extra careful when publishing.
My intent is to force the head version of shelf_web_socket to be used when running the web_socket_channel unit tests.
```
--- …
> Make shelf_web_socket a dev dependency

- CHANGELOG.md
- pubspec.yaml
- They are no longer needed now that `package:test` 1.25.2 is released.
---
<details>
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing). …
> Remove dependency_overrides

- CHANGELOG.md
- README.md
Fixes https://github.com/dart-lang/web_socket_channel/issues/358
---
<details>
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).
Note …
> Remove obsolete `WebSocketChannel.new` documentation.

- .github/workflows/test-package.yml
Supersedes https://github.com/dart-lang/web_socket_channel/pull/364
---
<details>
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).
Note …
> Remove `--fatal-infos` from `dart pub downgrade` analysis

- pubspec.yaml
Fixes #355 
Simply allow code 1000 like it should be by using the fix in web_socket dependency's last version 1.0.5
See  https://pub.dev/packages/web_socket/changelog
<details>
- Changes to packages require …
> Bump web_socket dependency 0.1.3 -> 0.1.5
